const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Product = require("./models/Product");

dotenv.config();

const products = [
  {
    name: "Syltherine",
    description: "Stylish cafe chair with premium wood finish and comfortable seating. Perfect for modern dining spaces.",
    price: 2500000,
    originalPrice: 3500000,
    discount: 30,
    category: "Dining",
    image: "/images/products/image1.png",
    stock: 15,
    rating: 4.5,
    reviewCount: 12,
    isFeatured: true,
    isNewArrival: false,
    tags: ["chair", "dining", "wood"],
    sku: "FRN-DIN-001",
  },
  {
    name: "Leviosa",
    description: "Elegant stylish cafe chair with ergonomic design. Built for comfort and style.",
    price: 2500000,
    category: "Dining",
    image: "/images/products/image2.png",
    stock: 20,
    rating: 4.2,
    reviewCount: 8,
    isFeatured: true,
    isNewArrival: false,
    tags: ["chair", "cafe", "modern"],
    sku: "FRN-DIN-002",
  },
  {
    name: "Lolito",
    description: "Luxury big sofa that redefines comfort. Premium upholstery with deep cushioning for ultimate relaxation.",
    price: 7000000,
    originalPrice: 14000000,
    discount: 50,
    category: "Living Room",
    image: "/images/products/image3.png",
    stock: 5,
    rating: 4.8,
    reviewCount: 24,
    isFeatured: true,
    isNewArrival: false,
    tags: ["sofa", "luxury", "living room"],
    sku: "FRN-LIV-001",
  },
  {
    name: "Respira",
    description: "Outdoor bar table and stool set. Weather-resistant materials with contemporary design.",
    price: 500000,
    category: "Outdoor",
    image: "/images/products/image4.png",
    stock: 30,
    rating: 4.0,
    reviewCount: 6,
    isFeatured: true,
    isNewArrival: true,
    tags: ["outdoor", "bar", "table"],
    sku: "FRN-OUT-001",
  },
  {
    name: "Grifo",
    description: "Night lamp with warm ambient lighting. Minimalist design that complements any bedroom aesthetic.",
    price: 1500000,
    category: "Bedroom",
    image: "/images/products/image6.png",
    stock: 40,
    rating: 4.3,
    reviewCount: 15,
    isFeatured: false,
    isNewArrival: true,
    tags: ["lamp", "bedroom", "lighting"],
    sku: "FRN-BED-001",
  },
  {
    name: "Muggo",
    description: "Small mug with elegant ceramic finish. Perfect for coffee enthusiasts who appreciate design.",
    price: 150000,
    category: "Dining",
    image: "/images/products/image7.png",
    stock: 100,
    rating: 4.1,
    reviewCount: 3,
    isFeatured: false,
    isNewArrival: true,
    tags: ["mug", "kitchen", "ceramic"],
    sku: "FRN-DIN-003",
  },
  {
    name: "Pingky",
    description: "Cute bed set with premium cotton linen. Soft pastel tones for a cozy bedroom atmosphere.",
    price: 7000000,
    originalPrice: 14000000,
    discount: 50,
    category: "Bedroom",
    image: "/images/products/image8.png",
    stock: 8,
    rating: 4.7,
    reviewCount: 19,
    isFeatured: false,
    isNewArrival: false,
    tags: ["bed", "bedroom", "cotton"],
    sku: "FRN-BED-002",
  },
  {
    name: "Potty",
    description: "Minimalist flower pot crafted from premium terracotta. Adds a natural touch to any space.",
    price: 500000,
    category: "Outdoor",
    image: "/images/products/Image5.png",
    stock: 50,
    rating: 3.9,
    reviewCount: 7,
    isFeatured: false,
    isNewArrival: true,
    tags: ["pot", "outdoor", "garden"],
    sku: "FRN-OUT-002",
  },
  {
    name: "Asgaard Sofa",
    description: "Premium handcrafted sofa with Scandinavian design. Features solid oak frame and premium fabric upholstery. The centerpiece of any modern living room.",
    price: 25000000,
    originalPrice: 30000000,
    discount: 17,
    category: "Living Room",
    image: "/images/products/Asgaardsofa3.png",
    stock: 3,
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isNewArrival: false,
    tags: ["sofa", "premium", "scandinavian", "handcrafted"],
    sku: "FRN-LIV-002",
  },
  {
    name: "Executive Desk",
    description: "Large executive desk with built-in cable management. Solid walnut construction with a matte finish.",
    price: 12000000,
    category: "Office",
    image: "/images/products/Rectangle36.png",
    stock: 7,
    rating: 4.6,
    reviewCount: 11,
    isFeatured: true,
    isNewArrival: false,
    tags: ["desk", "office", "walnut"],
    sku: "FRN-OFF-001",
  },
  {
    name: "Ergonomic Chair",
    description: "High-back ergonomic office chair with lumbar support, adjustable armrests, and breathable mesh back.",
    price: 8500000,
    originalPrice: 10000000,
    discount: 15,
    category: "Office",
    image: "/images/products/Rectangle37.png",
    stock: 12,
    rating: 4.4,
    reviewCount: 28,
    isFeatured: false,
    isNewArrival: true,
    tags: ["chair", "office", "ergonomic"],
    sku: "FRN-OFF-002",
  },
  {
    name: "Bella Dining Set",
    description: "6-seater dining table set with premium teak wood. Includes matching chairs with cushioned seats.",
    price: 18000000,
    originalPrice: 22000000,
    discount: 18,
    category: "Dining",
    image: "/images/products/Rectangle38.png",
    stock: 4,
    rating: 4.7,
    reviewCount: 16,
    isFeatured: true,
    isNewArrival: false,
    tags: ["dining", "table", "teak", "set"],
    sku: "FRN-DIN-004",
  },
  {
    name: "Cloud King Bed",
    description: "King-size platform bed with padded headboard and under-bed storage. Premium velvet upholstery.",
    price: 22000000,
    originalPrice: 28000000,
    discount: 21,
    category: "Bedroom",
    image: "/images/products/Rectangle39.png",
    stock: 6,
    rating: 4.8,
    reviewCount: 33,
    isFeatured: true,
    isNewArrival: false,
    tags: ["bed", "king", "velvet", "storage"],
    sku: "FRN-BED-003",
  },
  {
    name: "Zen Bookshelf",
    description: "Open-style bookshelf with asymmetric shelves. Perfect for displaying books, plants, and décor.",
    price: 6500000,
    category: "Living Room",
    image: "/images/products/Rectangle40.png",
    stock: 18,
    rating: 4.3,
    reviewCount: 9,
    isFeatured: false,
    isNewArrival: true,
    tags: ["bookshelf", "living room", "modern"],
    sku: "FRN-LIV-003",
  },
  {
    name: "Patio Lounge Set",
    description: "4-piece outdoor lounge set with weather-resistant rattan weave and UV-protected cushions.",
    price: 15000000,
    originalPrice: 20000000,
    discount: 25,
    category: "Outdoor",
    image: "/images/products/Rectangle41.png",
    stock: 5,
    rating: 4.5,
    reviewCount: 14,
    isFeatured: false,
    isNewArrival: false,
    tags: ["outdoor", "lounge", "patio", "rattan"],
    sku: "FRN-OUT-003",
  },
  {
    name: "Nordic Side Table",
    description: "Compact side table with Scandinavian design. Solid birch wood with natural grain finish.",
    price: 3200000,
    category: "Living Room",
    image: "/images/products/Rectangle43.png",
    stock: 25,
    rating: 4.2,
    reviewCount: 7,
    isFeatured: false,
    isNewArrival: true,
    tags: ["table", "side table", "nordic", "birch"],
    sku: "FRN-LIV-004",
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB for seeding");

    await Product.deleteMany({});
    console.log("🗑️  Cleared existing products");

    await Product.insertMany(products);
    console.log(`🌱 Seeded ${products.length} products`);

    await mongoose.connection.close();
    console.log("✅ Seeding complete. Connection closed.");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    process.exit(1);
  }
};

seedDB();
